#!/bin/bash

  compareJSON.py --or crab_projects/crab_MiniAOD_SingleMu1_DiMu_NOV27/results/processedLumis.json crab_projects/crab_MiniAOD_SingleMu2_DiMu_NOV27/results/processedLumis.json > crab_projects/processedLumis_SingleMu_DiMu_NOV27.json
  compareJSON.py --or crab_projects/crab_MiniAOD_SingleMu1_DiMu_TauDMAntiMedIso_NOV27/results/processedLumis.json crab_projects/crab_MiniAOD_SingleMu2_DiMu_TauDMAntiMedIso_NOV27/results/processedLumis.json > crab_projects/processedLumis_SingleMu_DiMu_TauDMAntiMedIso_NOV27.json
  compareJSON.py --or crab_projects/crab_MiniAOD_SingleMu1_DiMu_TauDM_Mass7p5to12_NOV27/results/processedLumis.json crab_projects/crab_MiniAOD_SingleMu2_DiMu_TauDM_Mass7p5to12_NOV27/results/processedLumis.json > crab_projects/processedLumis_SingleMu_DiMu_TauDM_Mass7p5to12_NOV27.json
  compareJSON.py --or crab_projects/crab_MiniAOD_SingleMu1_DiMu_TauDM_Mass81to101_NOV27/results/processedLumis.json crab_projects/crab_MiniAOD_SingleMu2_DiMu_TauDM_Mass81to101_NOV27/results/processedLumis.json > crab_projects/processedLumis_SingleMu_DiMu_TauDM_Mass81to101_NOV27.json
  compareJSON.py --or crab_projects/crab_MiniAOD_SingleMu1_DiMu_TauDMMedIso_NOV27/results/processedLumis.json crab_projects/crab_MiniAOD_SingleMu2_DiMu_TauDMMedIso_NOV27/results/processedLumis.json > crab_projects/processedLumis_SingleMu_DiMu_TauDMMedIso_NOV27.json
  compareJSON.py --or crab_projects/crab_MiniAOD_SingleMu1_DiMu_TauDM_NOV27/results/processedLumis.json  crab_projects/crab_MiniAOD_SingleMu2_DiMu_TauDM_NOV27/results/processedLumis.json > crab_projects/processedLumis_SingleMu_DiMu_TauDM_NOV27.json
exit 0
